sudo: false
language: ruby
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
before_install: gem install bundler -v 2.2.20
install: bundle install --jobs=3 --retry=3
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
